---
name: Browning
author: Posthaven
url: https//posthaven.com/
posts_per_page:
  include_in_settings: true
  default: 5
settings:
- id: header_bg_color
  label: Header Background
  type: color
- id: color_scheme
  label: Color scheme
  type: radio
  default: light
  options:
  - value: light
    label: Light background
  - value: dark
    label: Dark background