---
name: Browning
author: Posthaven
url: https//posthaven.com/
posts_per_page:
  include_in_settings: true
  default: 5
settings:
- id: link-color
  label: Link color
  type: color
  default: "#ec9405"
- id: color-scheme
  label: Color scheme
  type: radio
  default: light
  options:
  - value: light
    label: Light background
  - value: dark
    label: Dark background